version: '3.4'

networks:

  vlan20:
    driver: macvlan
    driver_opts:
      parent: eth0.20
    ipam:
      config:
        - subnet: 10.20.0.0/22

services:

  nat:
    build: .
    image: sofwerx/nat
    container_name: nat
    hostname: nat
    privileged: true
    environment:
      IP_ADDRESS: "10.20.0.1/22"
    networks:
      - default
      - vlan20
    restart: always

